### ISSUE TITLE
Research Printful API

### ISSUE THREAD

**Issue by acuba001** [acuba001/Sense_Makes_Math#13]
Research the API of the shirt provider that Eric uses. 
- [x] Read up capabilities of the API
- [x] Read up on the type of authentication needed for any type of transactions

**Comment by acuba001** [comment]
The shirt povider website is [www.printful.com](www.printful.com)

**Comment by thMthMnky** [comment]
This api has been partially implemented as of commit: 75dcaabe8a6635240e424f0b8347aa1794c444a3
