### ISSUE TITLE
Shows page to be grouped by YouTube playlist

### ISSUE THREAD

**Issue by acuba001** [acuba001/Sense_Makes_Math#25]
The page should group the YouTube channel's playlists into a slider component that with the title and description to the playlist above it.

**Comment by thMthMnky** [comment]
Included in commit: 99c8a8192f9a25b7dec02db43602621e2f054880, the route '/yt-posts/playlist' will return a list of playlistResources each containing a list of   video resources. No descriptive information is included in any of the resources as of this commit.
